services:
  - type: web
    name: Bluesky Label Watcher
    runtime: node
    autoDeploy: false
    plan: starter
    envVars:
      - key: BUN_VERSION
        value: 1.1.34
      - key: LABELER_APP_PASSWORD
        sync: false
      - key: LABELER_DID
        sync: false
      - key: LABELER_SOCKET_URL
        sync: false
      - key: LABELS_TO_LIST
        sync: false
      - key: LABELER_CURSOR_FILEPATH
        value: /var/data/cursor.txt
    buildCommand: bun i --frozen-lockfile
    startCommand: bun run start
    healthCheckPath: /health
    disk:
      name: local-files # Required field
      mountPath: /var/data # Required field
      sizeGB: 1 # Default: 10
version: "1"
